services:
  contentsafetyservice-api:
    image: ${DOCKER_REGISTRY-}contentsafetyserviceapi
    build:
      context: .
      dockerfile: ContentSafetyService/ContentSafetyService.Api/Dockerfile
   
  contentsafetyservice-dapr:
    image: "daprio/daprd:1.15.4" 
    depends_on:
      contentsafetyservice-api:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  contentservice-api:
    image: ${DOCKER_REGISTRY-}contentserviceapi
    build:
      context: .
      dockerfile: ContentService/ContentService.Api/Dockerfile

  contentservice-dapr:
    image: "daprio/daprd:1.15.4"
    depends_on:
      contentservice-api:
        condition: service_started
      rabbitmq:
        condition: service_healthy    

  subscriptionservice-api:
    image: ${DOCKER_REGISTRY-}subscriptionserviceapi
    build:
      context: .
      dockerfile: SubscriptionService/SubscriptionService.Api/Dockerfile


  voteservice-api:
    image: ${DOCKER_REGISTRY-}voteserviceapi
    build:
      context: .
      dockerfile: VoteService/VoteService.Api/Dockerfile



  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 15s
      timeout: 15s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
