services:
  contentsafetyservice.api:
    image: ${DOCKER_REGISTRY-}contentsafetyserviceapi
    build:
      context: .
      dockerfile: ContentSafetyService/ContentSafetyService.Api/Dockerfile

  contentservice.api:
    image: ${DOCKER_REGISTRY-}contentserviceapi
    build:
      context: .
      dockerfile: ContentService/ContentService.Api/Dockerfile


  subscriptionservice.api:
    image: ${DOCKER_REGISTRY-}subscriptionserviceapi
    build:
      context: .
      dockerfile: SubscriptionService/SubscriptionService.Api/Dockerfile


  voteservice.api:
    image: ${DOCKER_REGISTRY-}voteserviceapi
    build:
      context: .
      dockerfile: VoteService/VoteService.Api/Dockerfile

