services:
    #
    # Content Service
    #
  contentservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  contentservice-dapr:    
    command: >
      ./daprd
      --app-id contentservice-api
      --app-port 8080
      --resources-path /components
      --config /dapr/config.yaml
    volumes:
      - ./components/:/components
      - ./dapr/config.yaml:/dapr/config.yaml


    #   
    # Contentsafety Service
    #
  contentsafetyservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  contentsafetyservice-dapr:    
    command: >
      ./daprd
      --app-id contentsafetyservice-api
      --app-port 8080
      --resources-path /components
      --config /dapr/config.yaml
    volumes:
      - ./components/:/components
      - ./dapr/config.yaml:/dapr/config.yaml


    #
    # Subscription Service
    #
  subscriptionservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  subscriptionservice-dapr:    
    command: >
      ./daprd
      --app-id subscriptionservice-api
      --app-port 8080
      --resources-path /components
      --config /dapr/config.yaml
    volumes:
      - ./components/:/components
      - ./dapr/config.yaml:/dapr/config.yaml
      

    #
    # Vote Service
    #
  voteservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
  voteservice-dapr:    
    command: >
      ./daprd
      --app-id voteservice-api
      --app-port 8080
      --resources-path /components
      --config /dapr/config.yaml
    volumes:
      - ./components/:/components
      - ./dapr/config.yaml:/dapr/config.yaml

    #
    # Point Service
    #
  pointservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  pointservice-dapr:    
    command: >
      ./daprd
      --app-id pointservice-api
      --app-port 8080
      --resources-path /components
      --config /dapr/config.yaml
    volumes:
      - ./components/:/components
      - ./dapr/config.yaml:/dapr/config.yaml

  notificationservice-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  notificationservice-dapr:    
    command: >
      ./daprd
      --app-id notificationservice-api
      --app-port 8080
      --resources-path /components
      --config /dapr/config.yaml
    volumes:
      - ./components/:/components
      - ./dapr/config.yaml:/dapr/config.yaml

  gateway-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:    
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis

  zipkin:
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

volumes:
  rabbitmq_data:
  redis_data:

