name: ContentSafetyService - Test & Deploy

on:
  workflow_dispatch:  
  
  pull_request:
    branches: [ master ]
    paths:
      - 'ContentSafetyService/**'

jobs:
  build-contentsafetyservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET 9.0 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'
    
    - name: Run build
      run: dotnet build ContentSafetyService/ContentSafetyService.Api

  deploy:
    needs: build-contentsafetyservice
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image (ARM64)
      run: |
        docker build -t bilalkinali/contentsafetyservice-api:latest \
          -f ContentSafetyService/ContentSafetyService.Api/Dockerfile \
          .
        docker push bilalkinali/contentsafetyservice-api:latest
    
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd Projects/4SemForumProjekt
          docker pull bilalkinali/contentsafetyservice-api:latest
          docker compose up -d --force-recreate contentsafetyservice-api contentsafetyservice-dapr
          docker image prune -f
