name: CI - Build and Push NotificationService

on:
  workflow_dispatch:  # manual trigger from GitHub UI
  # Optional: uncomment below to auto-trigger on changes
  push:
    branches: [ master ]
    paths:
      - 'NotificationService/**'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image (ARM64)
      run: |
        docker build -t bilalkinali/notificationservice-api:latest \
          -f notificationservice/notificationservice.Api/Dockerfile \
          .
        docker push bilalkinali/notificationservice-api:latest
