name: VoteService - Build & Test

on:
  workflow_dispatch: 
  
  pull_request:
    branches: [ master ]

jobs:
  build-voteservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET 9.0 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'
    
    - name: Run build
      run: dotnet build VoteService/VoteService.Api

  test-voteservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: dotnet test VoteService/VoteService.Domain.Test --no-build
