name: CI - Build and Push Webservice Blazor WASM

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'WebService/**'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t bilalkinali/webservice-wasm:latest \
          -f WebService/Dockerfile \
          .
        docker push bilalkinali/webservice-wasm:latest
