name: Webservice - Build > Push > Pull > Compose

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'WebService/**'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t bilalkinali/webservice-wasm:latest \
          -f WebService/Dockerfile \
          .
        docker push bilalkinali/webservice-wasm:latest
    
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd Projects/4SemForumProjekt
          docker image pull bilalkinali/webservice-wasm:latest
          docker compose up -d webservice-wasm
          docker image prune -f
